# -*- coding: utf-8 -*-
"""customer_segment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKs9frjipWeObGQiLB6P90pub_4NZDcs
"""

import pandas as pd

import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestRegressor

from xgboost import XGBRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error

import matplotlib.pyplot as plt

import seaborn as sns

# Load the dataset

df = pd.read_csv('/content/drive/MyDrive/data/customer_segmentation.csv', encoding='latin1')

print("df shape:", df.shape)

print("df sample:\n", df.head())

# Preprocessing: Check for nulls and basic cleaning

df.dropna(inplace=True)

# Clean column names

df.columns = df.columns.str.strip()

print(df.columns)

# Convert 'InvoiceDate' to datetime

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# Drop missing CustomerIDs

df = df.dropna(subset=['CustomerID'])

# Snapshot date (latest invoice date + 1 day)

snapshot_date = df['InvoiceDate'].max() + pd.Timedelta(days=1)

# Feature Engineering: Recency, Frequency, AOV

customer_data = df.groupby('CustomerID').agg({
    'InvoiceDate': [
        lambda x: (snapshot_date - x.max()).days,  # Recency
        'count'  # Frequency
    ],
    'UnitPrice': 'mean'  # Average Order Value (AOV)
})

# Rename columns

customer_data.columns = ['Recency', 'Frequency', 'AOV']

customer_data.reset_index(inplace=True)

# Simulate Customer LTV (if real LTV not available)

np.random.seed(42)

customer_data['CustomerLTV'] = customer_data['Frequency'] * customer_data['AOV'] * np.random.uniform(1, 2, customer_data.shape[0])

# Features and Target

X = customer_data[['Recency', 'Frequency', 'AOV']]

y = customer_data['CustomerLTV']

# Train-test split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model Training - Random Forest

rf = RandomForestRegressor(random_state=42)

rf.fit(X_train, y_train)

# Optional Model Training - XGBoost

xgb = XGBRegressor(objective='reg:squarederror', random_state=42)

xgb.fit(X_train, y_train)

# Predictions

y_pred_rf = rf.predict(X_test)

y_pred_xgb = xgb.predict(X_test)

# Evaluation

print("\nRandom Forest Performance:")
print("MAE:", mean_absolute_error(y_test, y_pred_rf))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))

print("\nXGBoost Performance:")
print("MAE:", mean_absolute_error(y_test, y_pred_xgb))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_xgb)))

# Add Predicted LTV to customer_data

customer_data['PredictedLTV'] = rf.predict(X)

# Customer Segmentation based on Predicted LTV

customer_data['Segment'] = pd.qcut(customer_data['PredictedLTV'], q=4, labels=['Low', 'Mid-Low', 'Mid-High', 'High'])

print("\nFinal Segmented Customer Data:\n", customer_data.head())

# Visualization

plt.figure(figsize=(10,6))
sns.histplot(customer_data['PredictedLTV'], kde=True, color='skyblue')
plt.title('Predicted Customer LTV Distribution')
plt.xlabel('Predicted LTV')
plt.ylabel('Frequency')
plt.show()

# Save final results

customer_data.to_csv('/content/drive/MyDrive/data/final_ltv_predictions.csv', index=False)
print("\nFinal LTV predictions saved as 'final_ltv_predictions.csv'.")

